// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVo_oVArTYeyhj6-MzHj8QSyu2GbO46TQ',
    appId: '1:313163204080:web:e14c72546c43659d834935',
    messagingSenderId: '313163204080',
    projectId: 'culinae-28395',
    authDomain: 'culinae-28395.firebaseapp.com',
    storageBucket: 'culinae-28395.firebasestorage.app',
    measurementId: 'G-25CHMB9Z5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcg2IHnQg4okUeiRwoHV1qTKZDJbwhuM',
    appId: '1:313163204080:android:a4281156e22a2a7d834935',
    messagingSenderId: '313163204080',
    projectId: 'culinae-28395',
    storageBucket: 'culinae-28395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhlGZj8CEHk0XLeMqXBzlQKT_FBEyORE',
    appId: '1:313163204080:ios:08da1f44662656c1834935',
    messagingSenderId: '313163204080',
    projectId: 'culinae-28395',
    storageBucket: 'culinae-28395.firebasestorage.app',
    iosBundleId: 'com.example.culinae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLhlGZj8CEHk0XLeMqXBzlQKT_FBEyORE',
    appId: '1:313163204080:ios:08da1f44662656c1834935',
    messagingSenderId: '313163204080',
    projectId: 'culinae-28395',
    storageBucket: 'culinae-28395.firebasestorage.app',
    iosBundleId: 'com.example.culinae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVo_oVArTYeyhj6-MzHj8QSyu2GbO46TQ',
    appId: '1:313163204080:web:c939319a3b5bb5f1834935',
    messagingSenderId: '313163204080',
    projectId: 'culinae-28395',
    authDomain: 'culinae-28395.firebaseapp.com',
    storageBucket: 'culinae-28395.firebasestorage.app',
    measurementId: 'G-711J5GYM58',
  );
}
